# Generated by Django 3.1.6 on 2021-05-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='videojuego',
            options={'verbose_name': 'Videojuego', 'verbose_name_plural': 'Videojuegos'},
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='titulo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Título'),
        ),
    ]
