# Generated by Django 3.1.6 on 2021-05-16 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0002_auto_20210503_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='articulos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'], message='Sólo se permiten imágenes PNG, JPG o JPEG.')], verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio'),
        ),
    ]
