# Generated by Django 3.1.6 on 2021-05-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0003_auto_20210516_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
