# Generated by Django 3.1.6 on 2021-04-21 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210318_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.RegexValidator(code='rfc_invalido', message='El RFC no tiene un formato válido.', regex='^([A-Z][AEIOUX][A-Z]{2}\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])[HM](?:AS|B[CS]|C[CLMSH]|D[FG]|G[TR]|HG|JC|M[CNS]|N[ETL]|OC|PL|Q[TR]|S[PLR]|T[CSL]|VZ|YN|ZS)[B-DF-HJ-NP-TV-Z]{3}[A-Z\\d])(\\d)$')]),
        ),
    ]
