# Generated by Django 3.1.6 on 2021-04-29 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_curp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.RegexValidator(code='curp_invalida', message='La CURP no tiene un formato válido.', regex='^([A-Z][AEIOUX][A-Z]{2}\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])[HM](?:AS|B[CS]|C[CLMSH]|D[FG]|G[TR]|HG|JC|M[CNS]|N[ETL]|OC|PL|Q[TR]|S[PLR]|T[CSL]|VZ|YN|ZS)[B-DF-HJ-NP-TV-Z]{3}[A-Z\\d])(\\d)$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'], message='Sólo se permiten imágenes PNG, JPG o JPEG.')], verbose_name='Foto de perfil'),
        ),
    ]
